name: AttributePotion
author: 'Cordori'
version: '${project.version}'
api-version: 1.13
main: cordori.attributepotion.AttributePotion

softdepend:
  - AttributePlus
  - SX-Attribute
  - PlaceholderAPI
  - SkillAPI
  - DragonCore

commands:
  attributepotion:
    permission: admin
    aliases:
      - apn
