name: AttributePotion
author: 'Cordori'
version: '${project.version}'
api-version: 1.13
main: cordori.attributepotion.AttributePotion
depend:
  - AttributePlus
softdepend:
  - PlaceholderAPI
  - SkillAPI
  - DragonCore
commands:
  attributepotion:
    permission: admin
    aliases:
      - apn
