name: AttributePotion
author: 'Cordori'
version: '${project.version}'
api-version: 1.13
main: cordori.attributepotion.AttributePotion
description: 'A potion plugin that provides you with attributes or other features.'

softdepend:
  - AttributePlus
  - SX-Attribute
  - PlaceholderAPI
  - SkillAPI
  - DragonCore
  - AttributeSystem
  - OriginAttribute

commands:
  attributepotion:
    permission: admin
    aliases:
      - apn
